language: cpp
dist: trusty

compiler:
    - clang

addons:
  apt:
    sources:
        # add PPAs with more up-to-date toolchains
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
    packages:
        - clang-6.0
        - libsfml-dev

script:
    - make --no-print-directory release || travis_terminate 1
    - ./scripts/run_test_roms ./scripts/test_roms
